import { fold, tokenize } from './tokenizer.ts';
import { parseQuery, type QueryTerm } from './query.ts';
import { hubFolder } from './field-extract.ts';
import { fuzzyCandidates } from './fuzzy.ts';
import { rank, RANK, type ScoredDoc, type TermGroup } from './bm25f.ts';
import { FIELD } from './fields.ts';
import type { InvertedIndex } from './inverted-index.ts';
import type { DocType } from './fields.ts';

/** Fields searched when "Title only" is on. */
const TITLE_FIELDS = new Set<number>([FIELD.BASENAME, FIELD.ALIASES, FIELD.H1, FIELD.H2H3]);

export interface SearchResult {
  docId: number;
  path: string;
  basename: string;
  docType: DocType;
  tags: string[];
  mtime: number;
  score: number;
  /** Folded terms that matched — used to build/highlight the excerpt. */
  matched: string[];
}

export interface SearchOptions {
  limit?: number;
  /** Epoch ms for the recency decay. */
  now: number;
  /** Restrict matching to title fields (basename/aliases/headings). */
  titleOnly?: boolean;
  /** Extra folded path substrings a result must contain (folder chip). */
  pathFilters?: string[];
  /** Extra folded tag prefixes a result must carry (tag chip). */
  tagFilters?: string[];
  /** Only include docs modified at or after this epoch ms (date chip). */
  minMtime?: number;
  /** When the body Levenshtein fuzzy tier fires. Default 'on-sparse'. */
  bodyFuzzy?: 'off' | 'on-sparse' | 'always';
}

const DEFAULT_LIMIT = 20;
/** Below this many results, invoke the fuzzy fallback. */
const FUZZY_MIN = 5;
/** How many ranked candidates the title-intent pass looks at before slicing. */
const TITLE_POOL = 200;
/** A word typed before the last one still prefix-matches from this length. */
const PREFIX_MIN_LEN = 3;

/** idf weights for a set of terms — lets excerpt selection favor rare terms. */
export function excerptWeights(index: InvertedIndex, terms: string[]): Map<string, number> {
  const n = index.docCount;
  const weights = new Map<string, number>();
  for (const term of terms) {
    const df = index.getPostings(term)?.df ?? 0;
    weights.set(term, Math.log(1 + (n - df + 0.5) / (df + 0.5)));
  }
  return weights;
}

/**
 * Full keyword search: parse the query, build exact/prefix term groups (adding
 * a fuzzy tier only when results are sparse), apply path/tag/exclusion filters,
 * and rank. Pure — excerpts are generated by the caller from live file text.
 */
export function search(index: InvertedIndex, raw: string, opts: SearchOptions): SearchResult[] {
  const limit = opts.limit ?? DEFAULT_LIMIT;
  const parsed = parseQuery(raw);

  // Positive exact terms: query terms plus phrase tokens (so phrases retrieve).
  const exactSet = new Set<string>();
  for (const t of parsed.terms) exactSet.add(t.term);
  for (const phrase of parsed.phrases) for (const t of phrase) exactSet.add(t);
  if (exactSet.size === 0) return [];

  const groups: TermGroup[] = [...exactSet].map((term) => ({ variants: [term], weight: 1, key: term }));
  // Prefix expansion, excluding the exact term: always for the word being
  // typed, and for earlier words long enough to be a deliberate abbreviation
  // ("prod her" → Product Heroes).
  for (const t of parsed.terms) {
    if (!t.prefix && t.term.length < PREFIX_MIN_LEN) continue;
    const expansions = index.prefixTerms(t.term).filter((x) => x !== t.term);
    if (expansions.length > 0) groups.push({ variants: expansions, weight: RANK.prefixWeight, key: t.term });
  }

  // Merge query operators with chip filters.
  const pathFilters = [...parsed.pathFilters, ...(opts.pathFilters ?? [])];
  const tagFilters = [...parsed.tagFilters, ...(opts.tagFilters ?? [])];
  const allow = buildAllow(index, parsed.exclusions, pathFilters, tagFilters, opts.minMtime);
  const restrictFields = opts.titleOnly ? TITLE_FIELDS : undefined;

  const pool = Math.max(limit, TITLE_POOL);
  let scored = rank({
    index,
    groups,
    phrases: parsed.phrases,
    now: opts.now,
    limit: pool,
    allow,
    restrictFields,
  });

  // Fuzzy fallback, gated by mode: off = never; on-sparse = only when results
  // are sparse (default); always = run every query (fuzzyWeight contains noise).
  const fuzzyMode = opts.bodyFuzzy ?? 'on-sparse';
  const wantFuzzy =
    fuzzyMode === 'always' || (fuzzyMode === 'on-sparse' && scored.length < FUZZY_MIN);
  if (wantFuzzy) {
    const fuzzyGroups = [...groups];
    for (const t of parsed.terms) {
      const maxDist = t.term.length > 6 ? 2 : 1;
      const cands = fuzzyCandidates(t.term, index.allTerms, maxDist)
        .map((m) => m.term)
        .filter((x) => !exactSet.has(x));
      if (cands.length > 0) fuzzyGroups.push({ variants: cands, weight: RANK.fuzzyWeight, key: t.term });
    }
    if (fuzzyGroups.length > groups.length) {
      scored = rank({
        index,
        groups: fuzzyGroups,
        phrases: parsed.phrases,
        now: opts.now,
        limit: pool,
        allow,
        restrictFields,
      });
    }
  }

  scored = applyTitleIntent(index, scored, parsed.terms).slice(0, limit);

  return scored.map((s) => {
    const d = index.docEntry(s.docId)!;
    return {
      docId: s.docId,
      path: d.path,
      basename: d.basename,
      docType: d.docType,
      tags: d.tags,
      mtime: d.mtime,
      score: s.score,
      matched: s.matched,
    };
  });
}

/** One title word: its folded whole form plus its camelCase parts
 *  ("DeepAgent" → deepagent / deep, agent). */
export interface TitleWord {
  whole: string;
  parts: string[];
}

/** The words a note is titled by: its basename, or its folder for a hub note. */
export function titleWords(path: string, basename: string): TitleWord[] {
  const words: TitleWord[] = [];
  for (const run of (hubFolder(path, basename) ?? basename).split(/[^\p{L}\p{N}]+/u)) {
    if (!run) continue;
    const parts = tokenize(run).map((t) => t.text);
    const whole = fold(run);
    if (whole.length > 1) words.push({ whole, parts: parts.filter((p) => p !== whole) });
  }
  return words;
}

/** How well the title answers the query: 'exact' when query and title words
 *  cover each other, 'all' when every query word is in the title, else none. */
export function titleMatch(title: TitleWord[], terms: QueryTerm[]): 'exact' | 'all' | null {
  if (terms.length === 0 || title.length === 0) return null;
  const hits = (t: QueryTerm, word: string): boolean =>
    word === t.term ||
    ((t.prefix || t.term.length >= PREFIX_MIN_LEN) && word.startsWith(t.term));
  const hitsWord = (t: QueryTerm, w: TitleWord): boolean =>
    hits(t, w.whole) || w.parts.some((p) => hits(t, p));
  if (!terms.every((t) => title.some((w) => hitsWord(t, w)))) return null;
  const covered = (w: TitleWord): boolean =>
    terms.some((t) => hits(t, w.whole)) ||
    (w.parts.length > 0 && w.parts.every((p) => terms.some((t) => hits(t, p))));
  // A bare number in a title ("Job Search 2026") is a version or a year,
  // not a word the user is expected to type.
  return title.every((w) => covered(w) || /^\d+$/.test(w.whole)) ? 'exact' : 'all';
}

/** Boost the candidates whose title is what the user typed. Field weights alone
 *  can't do this: a transcript titled "Mario Miletta and Rosario" that repeats
 *  the name in its body outscores the note titled just "Mario Miletta". */
function applyTitleIntent(index: InvertedIndex, scored: ScoredDoc[], terms: QueryTerm[]): ScoredDoc[] {
  if (terms.length === 0) return scored;
  let changed = false;
  for (const s of scored) {
    const d = index.docEntry(s.docId);
    if (!d) continue;
    const match = titleMatch(titleWords(d.path, d.basename), terms);
    if (match === 'exact') s.score *= 1 + RANK.titleExact;
    else if (match === 'all') s.score *= 1 + RANK.titleAll;
    if (match) changed = true;
  }
  if (changed) scored.sort((a, b) => b.score - a.score);
  return scored;
}

/** Compose the filter predicate for exclusions + path + tag operators. */
function buildAllow(
  index: InvertedIndex,
  exclusions: string[],
  pathFilters: string[],
  tagFilters: string[],
  minMtime?: number,
): ((docId: number) => boolean) | undefined {
  if (
    exclusions.length === 0 &&
    pathFilters.length === 0 &&
    tagFilters.length === 0 &&
    minMtime === undefined
  ) {
    return undefined;
  }

  // Docs containing any excluded term (live only).
  const excluded = new Set<number>();
  for (const term of exclusions) {
    const entry = index.getPostings(term);
    if (!entry) continue;
    const p = entry.postings;
    let i = 0;
    while (i < p.length) {
      const docId = p[i++]!;
      const fieldMask = p[i++]!;
      for (let f = 0; f < 7; f++) if (fieldMask & (1 << f)) i++;
      if (fieldMask & (1 << 6)) {
        const posCount = p[i++]!;
        i += posCount;
      }
      if (!index.isDeleted(docId)) excluded.add(docId);
    }
  }

  return (docId: number): boolean => {
    if (excluded.has(docId)) return false;
    const d = index.docEntry(docId);
    if (!d) return false;
    if (minMtime !== undefined && d.mtime < minMtime) return false;
    if (pathFilters.length > 0) {
      const foldedPath = fold(d.path);
      if (!pathFilters.every((pf) => foldedPath.includes(pf))) return false;
    }
    if (tagFilters.length > 0) {
      if (!tagFilters.every((tf) => d.tags.some((tag) => tag.startsWith(tf)))) return false;
    }
    return true;
  };
}
