import { fold } from './tokenizer.ts';
import { parseQuery } from './query.ts';
import { fuzzyCandidates } from './fuzzy.ts';
import { rank, RANK, type TermGroup } from './bm25f.ts';
import { FIELD } from './fields.ts';
import type { InvertedIndex } from './inverted-index.ts';
import type { DocType } from './fields.ts';

/** Fields searched when "Title only" is on. */
const TITLE_FIELDS = new Set<number>([FIELD.BASENAME, FIELD.ALIASES, FIELD.H1, FIELD.H2H3]);

export interface SearchResult {
  docId: number;
  path: string;
  basename: string;
  docType: DocType;
  tags: string[];
  mtime: number;
  score: number;
  /** Folded terms that matched — used to build/highlight the excerpt. */
  matched: string[];
}

export interface SearchOptions {
  limit?: number;
  /** Epoch ms for the recency decay. */
  now: number;
  /** Restrict matching to title fields (basename/aliases/headings). */
  titleOnly?: boolean;
  /** Extra folded path substrings a result must contain (folder chip). */
  pathFilters?: string[];
  /** Extra folded tag prefixes a result must carry (tag chip). */
  tagFilters?: string[];
  /** Only include docs modified at or after this epoch ms (date chip). */
  minMtime?: number;
}

const DEFAULT_LIMIT = 20;
/** Below this many results, invoke the fuzzy fallback. */
const FUZZY_MIN = 5;

/** idf weights for a set of terms — lets excerpt selection favor rare terms. */
export function excerptWeights(index: InvertedIndex, terms: string[]): Map<string, number> {
  const n = index.docCount;
  const weights = new Map<string, number>();
  for (const term of terms) {
    const df = index.getPostings(term)?.df ?? 0;
    weights.set(term, Math.log(1 + (n - df + 0.5) / (df + 0.5)));
  }
  return weights;
}

/**
 * Full keyword search: parse the query, build exact/prefix term groups (adding
 * a fuzzy tier only when results are sparse), apply path/tag/exclusion filters,
 * and rank. Pure — excerpts are generated by the caller from live file text.
 */
export function search(index: InvertedIndex, raw: string, opts: SearchOptions): SearchResult[] {
  const limit = opts.limit ?? DEFAULT_LIMIT;
  const parsed = parseQuery(raw);

  // Positive exact terms: query terms plus phrase tokens (so phrases retrieve).
  const exactSet = new Set<string>();
  for (const t of parsed.terms) exactSet.add(t.term);
  for (const phrase of parsed.phrases) for (const t of phrase) exactSet.add(t);
  if (exactSet.size === 0) return [];

  const groups: TermGroup[] = [...exactSet].map((term) => ({ variants: [term], weight: 1 }));
  // Prefix expansion for the token(s) being typed, excluding the exact term.
  for (const t of parsed.terms) {
    if (!t.prefix) continue;
    const expansions = index.prefixTerms(t.term).filter((x) => x !== t.term);
    if (expansions.length > 0) groups.push({ variants: expansions, weight: RANK.prefixWeight });
  }

  // Merge query operators with chip filters.
  const pathFilters = [...parsed.pathFilters, ...(opts.pathFilters ?? [])];
  const tagFilters = [...parsed.tagFilters, ...(opts.tagFilters ?? [])];
  const allow = buildAllow(index, parsed.exclusions, pathFilters, tagFilters, opts.minMtime);
  const restrictFields = opts.titleOnly ? TITLE_FIELDS : undefined;

  let scored = rank({
    index,
    groups,
    phrases: parsed.phrases,
    now: opts.now,
    limit,
    allow,
    restrictFields,
  });

  // Fuzzy fallback: only when strong matching is sparse.
  if (scored.length < FUZZY_MIN) {
    const fuzzyGroups = [...groups];
    for (const t of parsed.terms) {
      const maxDist = t.term.length > 6 ? 2 : 1;
      const cands = fuzzyCandidates(t.term, index.allTerms, maxDist)
        .map((m) => m.term)
        .filter((x) => !exactSet.has(x));
      if (cands.length > 0) fuzzyGroups.push({ variants: cands, weight: RANK.fuzzyWeight });
    }
    if (fuzzyGroups.length > groups.length) {
      scored = rank({
        index,
        groups: fuzzyGroups,
        phrases: parsed.phrases,
        now: opts.now,
        limit,
        allow,
        restrictFields,
      });
    }
  }

  return scored.map((s) => {
    const d = index.docEntry(s.docId)!;
    return {
      docId: s.docId,
      path: d.path,
      basename: d.basename,
      docType: d.docType,
      tags: d.tags,
      mtime: d.mtime,
      score: s.score,
      matched: s.matched,
    };
  });
}

/** Compose the filter predicate for exclusions + path + tag operators. */
function buildAllow(
  index: InvertedIndex,
  exclusions: string[],
  pathFilters: string[],
  tagFilters: string[],
  minMtime?: number,
): ((docId: number) => boolean) | undefined {
  if (
    exclusions.length === 0 &&
    pathFilters.length === 0 &&
    tagFilters.length === 0 &&
    minMtime === undefined
  ) {
    return undefined;
  }

  // Docs containing any excluded term (live only).
  const excluded = new Set<number>();
  for (const term of exclusions) {
    const entry = index.getPostings(term);
    if (!entry) continue;
    const p = entry.postings;
    let i = 0;
    while (i < p.length) {
      const docId = p[i++]!;
      const fieldMask = p[i++]!;
      for (let f = 0; f < 7; f++) if (fieldMask & (1 << f)) i++;
      if (fieldMask & (1 << 6)) {
        const posCount = p[i++]!;
        i += posCount;
      }
      if (!index.isDeleted(docId)) excluded.add(docId);
    }
  }

  return (docId: number): boolean => {
    if (excluded.has(docId)) return false;
    const d = index.docEntry(docId);
    if (!d) return false;
    if (minMtime !== undefined && d.mtime < minMtime) return false;
    if (pathFilters.length > 0) {
      const foldedPath = fold(d.path);
      if (!pathFilters.every((pf) => foldedPath.includes(pf))) return false;
    }
    if (tagFilters.length > 0) {
      if (!tagFilters.every((tf) => d.tags.some((tag) => tag.startsWith(tf)))) return false;
    }
    return true;
  };
}
